name: tt-mobile
services:
  postgres:
    image: "postgres@sha256:43735280d1873da7ac9b6e7872b09c34f6d19283fd5f42f3fc22c982fbb0c0b1"
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - tt_mobile
volumes:
  data:
networks:
  tt_mobile:
    name: tt_mobile
